# Generated by Django 3.1.6 on 2021-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0002_auto_20210326_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userPassword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='food',
            field=models.ManyToManyField(to='CalorieCounter.Food'),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='user',
            field=models.ManyToManyField(blank=True, to='CalorieCounter.UserProfile'),
        ),
    ]
